=== Yanik2/xmlparsers/input.xsd
<?xml version="1.0" encoding="UTF-8"?>
<ns:schema xmlns:ns="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://flowers.com/flowers"
            xmlns="http://flowers.com/flowers"
                elementFormDefault="qualified">
    <ns:element name="flowers">
        <ns:complexType>
            <ns:sequence>
                <ns:element name="flower" type="Flower" maxOccurs="unbounded"/>
            </ns:sequence>
        </ns:complexType>
    </ns:element>

    <ns:complexType name="Flower">
        <ns:sequence>
            <ns:element name="name" type="ns:string"/>
            <ns:element name="soil" type="Soil"/>
            <ns:element name="origin" type="ns:string"/>
            <ns:element name="visualParams" type="VisualParams"/>
            <ns:element name="growingTips" type="GrowingTips"/>
            <ns:element name="multiplying" type="Multiplying"/>
        </ns:sequence>
    </ns:complexType>

    <ns:complexType name="VisualParams">
        <ns:sequence>
            <ns:element name="colorOfStem" type="ns:string"/>
            <ns:element name="colorOfLeaves" type="ns:string"/>
            <ns:element name="averageSize" type="ns:positiveInteger"/>
        </ns:sequence>
    </ns:complexType>

    <ns:complexType name="GrowingTips">
        <ns:sequence>
            <ns:element name="temperature" type="Temperature"/>
            <ns:element name="light" type="Light"/>
            <ns:element name="watering" type="ns:integer" default="0"/>
        </ns:sequence>
    </ns:complexType>

    <ns:complexType name="Soil">
        <ns:attribute name="typeOfSoil">
            <ns:simpleType>
                <ns:restriction base="ns:string">
                    <ns:enumeration value="podzolic"/>
                    <ns:enumeration value="ground"/>
                    <ns:enumeration value="sod-podzolic"/>
                </ns:restriction>
            </ns:simpleType>
        </ns:attribute>
    </ns:complexType>

    <ns:complexType name="Multiplying">
        <ns:attribute name="method">
            <ns:simpleType>
                <ns:restriction base="ns:string">
                    <ns:enumeration value="seed"/>
                    <ns:enumeration value="stalk"/>
                    <ns:enumeration value="leaves"/>
                </ns:restriction>
            </ns:simpleType>
        </ns:attribute>
    </ns:complexType>

    <ns:complexType name="Light">
        <ns:attribute name="condition">
            <ns:simpleType>
                <ns:restriction base="ns:string">
                    <ns:enumeration value="true"/>
                    <ns:enumeration value="false"/>
                </ns:restriction>
            </ns:simpleType>
        </ns:attribute>
    </ns:complexType>

    <ns:simpleType name="Temperature">
        <ns:restriction base="ns:integer">
            <ns:maxInclusive value="50"/>
            <ns:minExclusive value="0"/>
        </ns:restriction>
    </ns:simpleType>
</ns:schema>

=== Yanik2/xmlparsers/input.xml
<?xml version="1.0" encoding="utf-8"?>
<flowers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://flowers.com/flowers"
         xsi:schemaLocation="http://flowers.com/flowers input.xsd">
    <flower>
        <name>Rose</name>
        <soil typeOfSoil="podzolic"></soil>
        <origin>China</origin>
        <visualParams>
            <colorOfStem>Green</colorOfStem>
            <colorOfLeaves>Green</colorOfLeaves>
            <averageSize>10</averageSize>
        </visualParams>
        <growingTips>
            <temperature>26</temperature>
            <light condition="true"></light>
            <watering>1</watering>
        </growingTips>
        <multiplying method="seed"></multiplying>
    </flower>

    <flower>
        <name>Tulip</name>
        <soil typeOfSoil="ground"></soil>
        <origin>Afganistan</origin>
        <visualParams>
            <colorOfStem>Green</colorOfStem>
            <colorOfLeaves>Yellow</colorOfLeaves>
            <averageSize>5</averageSize>
        </visualParams>
        <growingTips>
            <temperature>20</temperature>
            <light condition="true"></light>
            <watering>2</watering>
        </growingTips>
        <multiplying method="leaves"></multiplying>
    </flower>

    <flower>
        <name>Magnolia</name>
        <soil typeOfSoil="sod-podzolic"></soil>
        <origin>Japan</origin>
        <visualParams>
            <colorOfStem>Red</colorOfStem>
            <colorOfLeaves>While</colorOfLeaves>
            <averageSize>7</averageSize>
        </visualParams>
        <growingTips>
            <temperature>30</temperature>
            <light condition="false"></light>
            <watering>3</watering>
        </growingTips>
        <multiplying method="stalk"></multiplying>
    </flower>

    <flower>
        <name>Violet</name>
        <soil typeOfSoil="ground"></soil>
        <origin>Ukraine</origin>
        <visualParams>
            <colorOfStem>Green</colorOfStem>
            <colorOfLeaves>Purple</colorOfLeaves>
            <averageSize>3</averageSize>
        </visualParams>
        <growingTips>
            <temperature>20</temperature>
            <light condition="false"></light>
            <watering>6</watering>
        </growingTips>
        <multiplying method="leaves"></multiplying>
    </flower>

    <flower>
        <name>Cactus</name>
        <soil typeOfSoil="podzolic"></soil>
        <origin>Mexico</origin>
        <visualParams>
            <colorOfStem>Green</colorOfStem>
            <colorOfLeaves>Green</colorOfLeaves>
            <averageSize>20</averageSize>
        </visualParams>
        <growingTips>
            <temperature>40</temperature>
            <light condition="false"></light>
            <watering>0</watering>
        </growingTips>
        <multiplying method="stalk"></multiplying>
    </flower>
</flowers>
